baseurl = "http://jspolice.com/"
languageCode = "en-us"
title = "JS Police"
theme = "hugo_theme_robust"
canonifyurls = true
paginate = 3
SectionPagesMenu = "main"

[Params]
  GoogleAnalyticsUserID = "UA-80126273-1"
  Author = "Petar Slovic"
  AuthorSite = "http://petarslovic.com"
  AuthorImage = "/images/petar.png"
  disqusShortname = "jspolice"
